version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    environment:
      SKIP_COMPOSER: 1
      WEBROOT: /var/www/html/public
      PHP_ERRORS_STDERR: 1
      RUN_SCRIPTS: 1
      REAL_IP_HEADER: 1
      LOG_CHANNEL: stderr
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
